# Generated by Django 3.2.9 on 2022-03-28 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.game'),
        ),
        migrations.AddField(
            model_name='player',
            name='numingame',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='PlayerGame',
        ),
    ]
